-- Bulk-assign a shared default PIN to every house seeded so far (data, not a
-- schema change, tracked as a migration per CLAUDE.md's convention), so
-- residents can log in immediately after the houses batch-import
-- (20260906160000_seed_houses.sql) instead of waiting for the admin to set
-- 64 PINs one by one through the edit-house screen. Any house can still get
-- its own individual PIN later (HOUS-02) -- this only touches houses that
-- don't have one yet.
--
-- The hash below is a pre-computed bcrypt/pgcrypto ("$2a$") hash supplied by
-- the admin -- NOT generated by this migration, so the actual PIN value
-- itself is never written to version control. It's directly compatible
-- with condo_verify_house_pin's `extensions.crypt(p_pin, h.pin_hash) =
-- h.pin_hash` comparison, the same as a hash produced by condo_hash_pin().
update condo_houses
  set pin_hash = '$2a$06$tGSTFu7i9GJeiUx3P2Wf9.WmelVH1DUTNKBTDdh394V7cnMRtYtg6',
      failed_pin_attempts = 0,
      pin_locked_until = null
where pin_hash is null;
